/*
 * Copyright (C) 2016 Texas Instruments Incorporated - http://www.ti.com/
 * ALL RIGHTS RESERVED
 */

#ifndef TIVX_KERNEL_OPTICAL_FLOW_PYR_LK_
#define TIVX_KERNEL_OPTICAL_FLOW_PYR_LK_

#ifdef __cplusplus
extern "C" {
#endif

#define TIVX_KERNEL_OPTICAL_FLOW_PYR_LK_OLD_PYRAMID_IDX (0U)
#define TIVX_KERNEL_OPTICAL_FLOW_PYR_LK_NEW_PYRAMID_IDX (1U)
#define TIVX_KERNEL_OPTICAL_FLOW_PYR_LK_PREVPTS_IDX (2U)
#define TIVX_KERNEL_OPTICAL_FLOW_PYR_LK_ESTIMATEDPTS_IDX (3U)
#define TIVX_KERNEL_OPTICAL_FLOW_PYR_LK_NEXTPTS_IDX (4U)
#define TIVX_KERNEL_OPTICAL_FLOW_PYR_LK_TERMINATION_IDX (5U)
#define TIVX_KERNEL_OPTICAL_FLOW_PYR_LK_EPSILON_IDX (6U)
#define TIVX_KERNEL_OPTICAL_FLOW_PYR_LK_NUM_ITERATIONS_IDX (7U)
#define TIVX_KERNEL_OPTICAL_FLOW_PYR_LK_USE_INITIAL_ESTIMATE_IDX (8U)
#define TIVX_KERNEL_OPTICAL_FLOW_PYR_LK_WINDOW_DIMENSION_IDX (9U)

#define TIVX_KERNEL_OPTICAL_FLOW_PYR_LK_MAX_PARAMS (10U)

#ifdef __cplusplus
}
#endif

#endif /* _TIVX_KERNEL_OPTICAL_FLOW_PYR_LK_ */


